#!/usr/bin/env bash
# Practice launcher for the Random Engine Failure script (Linux/macOS).
# Mirrors tools/practice-launch.bat.
#
# X-Plane does not forward command-line arguments to FlyWithLua, so instead of
# "passing a flag to X-Plane" we write the script's config file first, then
# start X-Plane. Same effect: a one-command way to control the session.
#
# NOTE: this rewrites random_engine_out.cfg from scratch, so any key it does not
# emit falls back to the script default. Keys it does not manage (notably
# clean_flight_chance, min_reduction/max_reduction) can be set via the
# environment overrides below. The scenario deck itself lives in
# random_engine_out.state and is NOT touched here — delete that file to reset it.
#
# Usage:
#   ./practice-launch.sh                 # normal flight (failures DISABLED)
#   ./practice-launch.sh armed           # failures enabled with defaults
#   ./practice-launch.sh armed 10        # enabled, 10 min of quiet flying first
#   ./practice-launch.sh armed 0 50      # enabled, 50-minute session (2 pomodoros)
#
# Optional environment overrides:
#   XPLANE_PATH          Install dir      (default: ~/X-Plane 12)
#   XPLANE_EXE           Executable name  (default: X-Plane-x86_64; macOS: "X-Plane 12.app")
#   CLEAN_FLIGHT_CHANCE  Share of flights with no failure (default: script default)
#   FAILURE_DEADLINE     Fire by this minute of flight at the latest (0 = off)
#   DEBUG_REVEAL         true = show the drawn card and countdown in the GUI
set -euo pipefail

XPLANE_PATH="${XPLANE_PATH:-${HOME}/X-Plane 12}"
SCRIPTS_DIR="${XPLANE_PATH}/Resources/plugins/FlyWithLua/Scripts"
CFG="${SCRIPTS_DIR}/random_engine_out.cfg"

MODE="${1:-}"
DELAY="${2:-0}"
SESSION="${3:-25}"

if [[ "${MODE,,}" == "armed" ]]; then
    ENABLED="true"
    echo "[practice] Arming random engine failure (session: ${SESSION} min, quiet for the first ${DELAY} min of flight)."
else
    ENABLED="false"
    echo "[practice] Normal flight - random engine failure DISABLED."
fi

if [[ ! -d "${SCRIPTS_DIR}" ]]; then
    echo "[practice] ERROR: FlyWithLua Scripts folder not found:" >&2
    echo "            ${SCRIPTS_DIR}" >&2
    echo "            Set XPLANE_PATH or install FlyWithLua first." >&2
    exit 1
fi

# Write the config the Lua script reads on load.
cat > "${CFG}" <<EOF
# Auto-generated by practice-launch.sh - safe to overwrite.
enabled = ${ENABLED}
session_minutes = ${SESSION}
start_delay_minutes = ${DELAY}
EOF

if [[ -n "${CLEAN_FLIGHT_CHANCE:-}" ]]; then
    echo "clean_flight_chance = ${CLEAN_FLIGHT_CHANCE}" >> "${CFG}"
fi
if [[ -n "${FAILURE_DEADLINE:-}" ]]; then
    echo "failure_deadline_minutes = ${FAILURE_DEADLINE}" >> "${CFG}"
fi
if [[ -n "${DEBUG_REVEAL:-}" ]]; then
    echo "debug_reveal = ${DEBUG_REVEAL}" >> "${CFG}"
fi

echo "[practice] Wrote ${CFG}"

# Resolve how to launch X-Plane.
if [[ "$(uname -s)" == "Darwin" ]]; then
    APP="${XPLANE_EXE:-X-Plane 12.app}"
    APP_PATH="${XPLANE_PATH}/${APP}"
    if [[ ! -d "${APP_PATH}" ]]; then
        echo "[practice] ERROR: X-Plane app not found at ${APP_PATH}" >&2
        exit 1
    fi
    echo "[practice] Launching ${APP_PATH}"
    open "${APP_PATH}"
else
    EXE="${XPLANE_EXE:-X-Plane-x86_64}"
    EXE_PATH="${XPLANE_PATH}/${EXE}"
    if [[ ! -x "${EXE_PATH}" ]]; then
        echo "[practice] ERROR: X-Plane executable not found/executable at ${EXE_PATH}" >&2
        exit 1
    fi
    echo "[practice] Launching ${EXE_PATH}"
    "${EXE_PATH}" &
fi
